version: "3"
services: 
  backend:
    image: filipton/smarty-backend:latest
    restart: unless-stopped
    environment:
      SECRET: SuperSecretSecret1234
  frontend:
    image: filipton/smarty-frontend:latest
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:8090/api
  nginx:
    image: filipton/smarty-nginx:latest
    restart: unless-stopped
    ports:
      - 8090:80
